default_model = "nllb"
target_lang = "eng_Latn"
device = "cpu"
device_indices = [0]

[server]
host = "0.0.0.0"
port = 8080

[aliases]
"nllb" = "nllb-200-distilled-1.3B"

[models]
[models."nllb-200-distilled-1.3B"]
path = "./models/nllb-200-distilled-1.3B/quant_8"
tokenizer_path = "./models/nllb-200-distilled-1.3B"
model_type = "nllb"

[models."t5-small"]
path = "./models/t5-small"
model_type = "t5"

[models."nllb-200-distilled-600M"]
path = "./models/nllb-200-distilled-600M"
model_type = "nllb"

[models."nllb-200-3.3B"]
tokenizer_path = "./models/nllb-200-3.3B"
path = "./models/nllb-200-3.3B/quant_32"
model_type = "nllb"
