version: '3.8'

services:
  ctranslate2-server:
    image: any35/ctranslate2-server:latest # Or :cpu / :gpu
    container_name: ctranslate2-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./models:/app/models
      - ./config.toml:/app/config.toml
    environment:
      - RUST_LOG=info
      # Overrides
      # - SERVER_PORT=8080
    
    # Uncomment for GPU support (requires nvidia-container-toolkit)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
